"""Add user_id to Auction

Revision ID: d9202d301f19
Revises: 10b5c6e84e30
Create Date: 2025-01-14 18:31:33.508659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9202d301f19'
down_revision = '10b5c6e84e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('time_long',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('goods_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('auction_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('seller_now')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_now', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auction_ibfk_2', 'user', ['seller_now'], ['user_id'])
        batch_op.alter_column('goods_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_long',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
